# docker-compose file to start up Laravel application in https://example.com
# to start the container run:
#       docker-compose up -d
#
# Note: Bind mounts for laravel
#       ./www:/var/www -- Laravel app base folder
#       ./www/public:/var/www/html -- Apache DocumentRoot is mapped to Laravel public folder
#
# Note2: containrrr/watchtower service will auto update this container

version: "3"

services:
  videohub:
    image: rsubr/php-apache-ubuntu:noble
    container_name: # container name
    restart: always

    ports:
      - 8000:80

    volumes:
      - ./www:/var/www
      - ./www/public:/var/www/html
      - ./etc/php/8.3/apache2/conf.d/99-local.ini:/etc/php/8.3/apache2/conf.d/99-local.ini:ro
      - ./etc/apache2/mods-enabled/mpm_prefork.conf:/etc/apache2/mods-enabled/mpm_prefork.conf:ro

    mem_limit: 2G

    labels:
      - com.centurylinklabs.watchtower.enable=true
        # - traefik.enable=true
        # - traefik.http.routers.prosafe.rule=Host(`example.com`)
        # - traefik.http.routers.prosafe.tls=true
        # - traefik.http.routers.prosafe.tls.certresolver=lets-encrypt

    depends_on:
      - pgsql

  pgsql:
      image: postgres:13
      container_name: # container name
      restart: always
  
      environment:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  
      ports:
        - 5432:5432
  
      volumes:
        - ./pgsql-data:/var/lib/postgresql/data
        - ./pgsql-conf/postgresql.conf:/etc/postgresql/postgresql.conf